### ISSUE TITLE
dryrun exits with error when adding a new team

### ISSUE THREAD

**Issue by venkatamutyala** [OpenRailAssociation/github-org-manager#52]
Steps to recreate:
1) Add a new team
2) Run with dryrun enabled
3) All the logs look fine and then at the very end the app crashes. 

I believe it's trying to grab the repos for the team that hasn't been added yet during the dryrun.

**Comment by mxmehl** [comment]
Thanks for the report. Yes, I knew this problem existed but just today found time to fix it.

May I please ask you to provide logs next time, ideally when running the program with the `--debug` flag?
